//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("EC_WarehouseMapping")]
    public partial class EC_WarehouseMapping
    {
		/// <summary>
    /// 
    /// </summary>
		
	[Key]
		
	public int Id { get; set; }
		/// <summary>
    /// 易仓仓库ID
    /// </summary>
		
	public int? EC_WarehouseId { get; set; }
		public EC_Warehouse EC_WarehouseE { get; set; }
			/// <summary>
    /// 仓库ID
    /// </summary>
		
	public int? Sys_WarehouseId { get; set; }
		public Sys_Warehouse Sys_WarehouseE { get; set; }
		   
    }
}

