//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Res_Country")]
    public partial class Res_Country
    {
		/// <summary>
    /// 国家ID
    /// </summary>
		
	[Key]
		
	public int CountryId { get; set; }
		/// <summary>
    /// 国家二字码
    /// </summary>
		
	public string CountryCode { get; set; }
		/// <summary>
    /// 国家中文名
    /// </summary>
		
	public string CountryName { get; set; }
		/// <summary>
    /// 国家英文名
    /// </summary>
		
	public string CountryNameEn { get; set; }
	   
    }
}

