//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-01-30 10:54:23
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Res_GroupDictionary")]
    public partial class Res_GroupDictionary
    {

	   /// <summary>
     	/// 
     	/// </summary>
		[Key]
		public int Id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Code { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Name { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string DGroup { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int Sort { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime CreateDate { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int CreateUid { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime WriteDate { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int WriteUid { get; set; }

		   
    }
}

