//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Res_Selection")]
    public partial class Res_Selection
    {
		/// <summary>
    /// ID
    /// </summary>
		
	[Key]
		
	public int Id { get; set; }
		/// <summary>
    /// 代码
    /// </summary>
		
	public string Code { get; set; }
		/// <summary>
    /// 名称
    /// </summary>
		
	public string ZhName { get; set; }
		/// <summary>
    /// 英文名称
    /// </summary>
		
	public string EnName { get; set; }
		/// <summary>
    /// 分组标识
    /// </summary>
		
	public string SelectionGroup { get; set; }
		/// <summary>
    /// 排序
    /// </summary>
		
	public int Sort { get; set; }
		/// <summary>
    /// 创建时间
    /// </summary>
		
	public DateTime CreateDate { get; set; }
		/// <summary>
    /// 创建人
    /// </summary>
		
	public int CreateUid { get; set; }
		/// <summary>
    /// 最后修改时间
    /// </summary>
		
	public DateTime WriteDate { get; set; }
		/// <summary>
    /// 最后修改人
    /// </summary>
		
	public int WriteUid { get; set; }
	   
    }
}

