//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Sys_PartnerAddress")]
    public partial class Sys_PartnerAddress
    {
		/// <summary>
    /// 
    /// </summary>
		
	[Key]
		
	public int Id { get; set; }
		/// <summary>
    /// 国家
    /// </summary>
		
	public string CountryCode { get; set; }
		/// <summary>
    /// 省/州
    /// </summary>
		
	public string StateCode { get; set; }
		/// <summary>
    /// 城市
    /// </summary>
		
	public string CityCode { get; set; }
		/// <summary>
    /// 区域
    /// </summary>
		
	public string Area { get; set; }
		/// <summary>
    /// 详细地址
    /// </summary>
		
	public string DetailAddress { get; set; }
		/// <summary>
    /// 联系人
    /// </summary>
		
	public string Contact { get; set; }
		/// <summary>
    /// 手机号
    /// </summary>
		
	public string Mobile { get; set; }
		/// <summary>
    /// 电话
    /// </summary>
		
	public string Phone { get; set; }
		/// <summary>
    /// Email
    /// </summary>
		
	public string Email { get; set; }
		/// <summary>
    /// 地址类型
    /// </summary>
		
	public string AddressType { get; set; }
		/// <summary>
    /// 
    /// </summary>
		
	public int? PartnerId { get; set; }
		/// <summary>
    /// 
    /// </summary>
		
	public bool IsDefaultAdd { get; set; }
	   
    }
}

