//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Sys_GoodsCategory")]
    public partial class Sys_GoodsCategory
    {
		/// <summary>
    /// 
    /// </summary>
		
	[Key]
		
	public int Id { get; set; }
		/// <summary>
    /// 商品分类代码
    /// </summary>
		
	public string Code { get; set; }
		/// <summary>
    /// 商品分类名称
    /// </summary>
		
	public string Name { get; set; }
		/// <summary>
    /// 说明
    /// </summary>
		
	public string Remark { get; set; }
		/// <summary>
    /// 上级商品名称
    /// </summary>
		
	public int ParentId { get; set; }
	public Sys_GoodsCategory Parent{get;set;}
		/// <summary>
    /// 分类级别
    /// </summary>
		
	public int CategoryLevel { get; set; }
		/// <summary>
    /// 创建时间
    /// </summary>
		
	public DateTime? CreateDate { get; set; }
		/// <summary>
    /// 创建人
    /// </summary>
		
	public int? CreateUid { get; set; }
		/// <summary>
    /// 更新时间
    /// </summary>
		
	public DateTime? WriteDate { get; set; }
		/// <summary>
    /// 更新人
    /// </summary>
		
	public int? WriteUid { get; set; }
		/// <summary>
    /// 税率
    /// </summary>
		
	public decimal? TaxRate { get; set; }
	   
    }
}

