//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-01-31 18:28:26
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Sys_GoodsCategory")]
    public partial class Sys_GoodsCategory
    {
	/// <summary>
    /// 
    /// </summary>
		
	[Key]
		
	public int Id { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public string Code { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public string Name { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public string Remark { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public int ParentId { get; set; }
	public Sys_GoodsCategory Parent{get;set;}
	/// <summary>
    /// 
    /// </summary>
		
	public int CategoryLevel { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public DateTime? CreateDate { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public int? CreateUid { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public DateTime? WriteDate { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public int? WriteUid { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public decimal? TaxRate { get; set; }
	   
    }
}

