//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-01-31 18:28:26
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Sys_Goods")]
    public partial class Sys_Goods
    {
	/// <summary>
    /// 
    /// </summary>
		
	[Key]
		
	public int Id { get; set; }
	/// <summary>
    /// 商品编码
    /// </summary>
		
	public string Code { get; set; }
	/// <summary>
    /// 商品名称
    /// </summary>
		
	public string Name { get; set; }
	/// <summary>
    /// 虚拟产品
    /// </summary>
		
	public bool NoStock { get; set; }
	/// <summary>
    /// 使用批次号
    /// </summary>
		
	public bool UsingBatch { get; set; }
	/// <summary>
    /// 使用序列号
    /// </summary>
		
	public bool ForceBatchOne { get; set; }
	/// <summary>
    /// 商品图片
    /// </summary>
		
	public string ImagePath { get; set; }
	/// <summary>
    /// 供应商
    /// </summary>
		
	public string SupplierCode { get; set; }
	/// <summary>
    /// 零售价
    /// </summary>
		
	public decimal? Price { get; set; }
	/// <summary>
    /// 条码
    /// </summary>
		
	public string Barcode { get; set; }
	/// <summary>
    /// 
    /// </summary>
		
	public string Note { get; set; }
	/// <summary>
    /// 商品类型
    /// </summary>
		
	public int GoodsCategoryId { get; set; }
		public Sys_GoodsCategory Sys_GoodsCategoryE { get; set; }
		/// <summary>
    /// 计量单位
    /// </summary>
		
	public int UomId { get; set; }
	/// <summary>
    /// 成本
    /// </summary>
		
	public decimal Cost { get; set; }
	/// <summary>
    /// 税率
    /// </summary>
		
	public decimal? TaxRate { get; set; }
	/// <summary>
    /// 不可销售
    /// </summary>
		
	public bool? NotSaleAble { get; set; }
	/// <summary>
    /// 启用
    /// </summary>
		
	public bool? Active { get; set; }
	/// <summary>
    /// 净重
    /// </summary>
		
	public decimal? NetWeight { get; set; }
	/// <summary>
    /// 重量
    /// </summary>
		
	public decimal? Weight { get; set; }
	   
    }
}

