//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-01-29 18:18:24
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Sys_WhMove")]
    public partial class Sys_WhMove
    {

	   /// <summary>
     	/// 
     	/// </summary>
		[Key]
		public long Id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string MoveCode { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime CreateDate { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime WriteDate { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int Total { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int CreateUserId { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int CustomerId { get; set; }

		   
    }
}

