//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Sys_Customer")]
    public partial class Sys_Customer
    {
		/// <summary>
    /// 
    /// </summary>
		
	[Key]
		
	public long Id { get; set; }
		/// <summary>
    /// 客户名称
    /// </summary>
		
	public string Name { get; set; }
		/// <summary>
    /// 客户编号
    /// </summary>
		
	public string CustomerCode { get; set; }
		/// <summary>
    /// 创建时间
    /// </summary>
		
	public DateTime CreateDate { get; set; }
		/// <summary>
    /// 更新时间
    /// </summary>
		
	public DateTime WriteDate { get; set; }
		/// <summary>
    /// 电话
    /// </summary>
		
	public string Phone { get; set; }
		/// <summary>
    /// 手机号
    /// </summary>
		
	public string Mobile { get; set; }
		/// <summary>
    /// 客户等级
    /// </summary>
		
	public int? CustomerLevel { get; set; }
		/// <summary>
    /// 总消费金额
    /// </summary>
		
	public decimal? TotalAmount { get; set; }
		/// <summary>
    /// 最后一次购买时间
    /// </summary>
		
	public DateTime? LastBuyDate { get; set; }
		/// <summary>
    /// 最后一次购买金额
    /// </summary>
		
	public decimal? LastBuyAmount { get; set; }
	   
    }
}

