//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-01-31 18:28:26
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace LQExtension.Model
{	
   
   [Table("Sys_WarehouseArea")]
    public partial class Sys_WarehouseArea
    {
	/// <summary>
    /// 货区编号
    /// </summary>
		[ExplicitKey]
		
	public string WarehouseAreaCode { get; set; }
		public Sys_Warehouse Sys_WarehouseE { get; set; }
		/// <summary>
    /// 
    /// </summary>
		
	public string Barcode { get; set; }
	/// <summary>
    /// 归属仓库
    /// </summary>
		
	public string WarehouseCode { get; set; }
	/// <summary>
    /// 货区名称
    /// </summary>
		
	public string WarehouseAreaName { get; set; }
	/// <summary>
    /// 创建人
    /// </summary>
		
	public int CreateUid { get; set; }
	/// <summary>
    /// 最后更信人
    /// </summary>
		
	public int WriteUid { get; set; }
	/// <summary>
    /// 创建时间
    /// </summary>
		
	public DateTime CreateDate { get; set; }
	/// <summary>
    /// 最后更新时间
    /// </summary>
		
	public DateTime WriteDate { get; set; }
	/// <summary>
    /// 货区类型
    /// </summary>
		
	public string WarehouaeAreaTypeDic { get; set; }
	   
    }
}

